name: Test across NodeJS versions

on:
  push:
    paths:
      - '!.*'
      - '!*.code-workspace'
      - '!*.md'
      - '**/*'
      - '!.github/**/*'
      - '.github/workflows/test.yml'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix['node-version'] }}
        cache: 'npm'
    - run: npm ci
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "users.json"
        json: ${{ secrets.TEST_STEAM_ACCOUNTS }}
        dir: 'tests/kards/'
    - run: npm test
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage/coverage-final.json
        flags: ${{ matrix.node-version }}
        fail_ci_if_error: true
        verbose: true
